language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t cpedreira/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cpedreira/docker-react npm run test